Kevin db
MarkFuller1/BNU pull request #37
Opened 2019-11-14 20:04 UTC by Kevin-Joseph

2019-11-14 20:09 UTC, MarkFuller1 requested changes
can you remove the lines

2019-11-14 20:09 UTC, MarkFuller1 commented on BCC/src/main/java/BNU/presentation/MainView.java
> +                "jdbc:postgresql://127.0.0.1:5432/BCC", "postgres", "aspartame")) {
All of this code is going to be replaced by the DB wrapper, so we can remove it from here

2019-11-19 13:45 UTC, Kevin-Joseph commented
Yeah I can remove these lines, I will figure out how to.

2019-11-19 13:49 UTC, Kevin-Joseph reviewed
Took out the db connection code.

2019-11-25 21:30 UTC, MarkFuller1 approved these changes

2019-12-01 20:53 UTC, merged